lg <- lg %>%
  mutate(INTERVIEWER.S.NAME.1 = case_when(
    INTERVIEWER.S.NAME.1 == "09015165618" ~ "OLUWAFEMI",
    INTERVIEWER.S.NAME.1 == "08169024817" ~ "ANUOLUWAPO",
    INTERVIEWER.S.NAME.1 == "08183469333" ~ "VICTORIA",
    INTERVIEWER.S.NAME.1 == "1GOKI" ~ "IGOKI",
    INTERVIEWER.S.NAME.1 == "1GOK" ~ "IGOKI",
    INTERVIEWER.S.NAME.1 == "ESTHER DANIEL" ~ "ANUOLUWAPO",
    INTERVIEWER.S.NAME.1 == "KEHINDE ADEGBUYI" ~ "KEHINDE",
    INTERVIEWER.S.NAME.1 == "MI6" ~ "MICHAEL",
    INTERVIEWER.S.NAME.1 == "MORENIKEJI" ~ "ZAINAB",
    INTERVIEWER.S.NAME.1 == "Oluwafemi" ~ "OLUWAFEMI",
    INTERVIEWER.S.NAME.1 == "Z" ~ "ZAINAB",
    INTERVIEWER.S.NAME.1 == "ZAI" ~ "ZAINAB",
    TRUE ~ INTERVIEWER.S.NAME.1  # Keep the original value if no match
  ))
